(cl:defpackage motoman_msgs-msg
  (:use )
  (:export
   "<DYNAMICJOINTSGROUP>"
   "DYNAMICJOINTSGROUP"
   "<DYNAMICJOINTPOINT>"
   "DYNAMICJOINTPOINT"
   "<DYNAMICJOINTSTATE>"
   "DYNAMICJOINTSTATE"
   "<DYNAMICJOINTTRAJECTORYFEEDBACK>"
   "DYNAMICJOINTTRAJECTORYFEEDBACK"
   "<DYNAMICJOINTTRAJECTORY>"
   "DYNAMICJOINTTRAJECTORY"
  ))

